Models/Bill.cs
using System;
using System.Collections.Generic;

namespace ShoppingWEB.Models;

public partial class Bill
{
    public string Id { get; set; } = Guid.NewGuid().ToString();


    public double? Total { get; set; }

    public string? PaymentMethod { get; set; }

    public int? Quantity { get; set; }

    public string? DeliveryId { get; set; }

    public string? UserId { get; set; }

    public DateTime? Date { get; set; }

    public virtual DeliveryType? Delivery { get; set; }

    public virtual PaymentMethod? PaymentMethodNavigation { get; set; }

    public virtual ICollection<BillItem> BillItems { get; set; } = new List<BillItem>();
}

Areas/Admin/Controllers/BillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoppingWEB.Models;

namespace ShoppingWEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BillController : Controller
    {
        private readonly ShoppingContext _context;

        public BillController(ShoppingContext context)
        {
            _context = context;
        }

        // GET: Admin/Bill
        public async Task<IActionResult> Index()
        {
            var shoppingContext = await _context.Bills.ToListAsync();
            return View(shoppingContext);
        }

        // GET: Admin/Bill/Details/5
        public async Task<IActionResult> Detail(string? id)
        {
            // if (id == null || _context.Bills == null)
            // {
            //     return NotFound();
            // }

            var bill = await _context.Bills
                .Include(b => b.Delivery)
                .Include(b => b.PaymentMethodNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            // if (bill == null)
            // {
            //     return NotFound();
            // }

            return View(bill);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,TypeProductId,Total,PaymentMethod,Quantity,DeliveryId")]
            Bill bill)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["DeliveryId"] = new SelectList(_context.DeliveryTypes, "Id", "Id", bill.DeliveryId);
            ViewData["PaymentMethod"] = new SelectList(_context.PaymentMethods, "Id", "Id", bill.PaymentMethod);
            // TODO return
            return View("Index");
        }
    }
}

Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingWEB.Models;

namespace ShoppingWEB.Controllers;

public class BillController : Controller
{
    private ShoppingContext _context;

    public BillController(ShoppingContext context)
    {
        _context = context;
    }

    // GET
    public IActionResult Index(string? id)
    {
        var bill = _context.Bills.FirstOrDefault(b => b.Id == id);
        return View(bill);
    }
}

Views/Bill/Index.cshtml
@model ShoppingWEB.Models.Bill
@inject ShoppingContext ShoppingContext

@{
    ViewBag.Title = "Hóa đơn";
    Layout = "_Layout";
    var user = ShoppingContext.Users.FirstOrDefault(model => model.Id == Model.UserId);
}



<div class="bg-white product-container">
    <div class="d-flex overflow-hidden h-100">
        <div class="product-item d-flex flex-column flex-grow-1">
            <div class="product-item__header d-flex p-3 w-100  flex-grow-1 justify-content-between px-5">
                @*<div class="d-flex align-items-center">Chi tiết hóa đơn</div>
                <div class="d-flex align-items-center">
                </div>

                <div class="d-flex align-items-center gap-2">
                    <a class="btn btn-primary" asp-controller="Bill" asp-action="Index">Quay Lại</a>
                </div>*@
            </div>
            @*<div class="product-item__content">
                <div class="table-container">
                    <table>
                        <thead>
                        <tr>
                            <th>STT</th>
                            <th>Ảnh</th>
                            <th>Tên Sản Phẩm</th>
                            <th>Phân loại hàng</th>
                            <td>Size</td>
                            <th>Giá</th>
                            <th>Số Lượng</th>
                            <th>Tổng Tiền</th>
                        </tr>
                        </thead>
                        <tbody>
                        <div class="bill-item d-flex flex-column">
                            @{
                                var modelBillItem = Model.BillItems.ToList();
                            }
                            @for (var i = 0; i < modelBillItem.Count; i++)
                            {
                                <tr>

                                    <td>@(i+1)</td>
                                    <td >

                                        @{
                                            var i1 = i;
                                        }
                                        <a asp-controller="Detail" asp-action="Index" asp-route-id="@modelBillItem[i1].TypeProduct!.Product!.Id">
                                            <div class="image" style="margin-right: 10px;!important;">
                                                <img width="100px" src="@modelBillItem[i1].TypeProduct!.ImagePath" class="img-sanpham"/>
                                            </div>
                                        </a>
                                    </td>
                                    $1$ TODO design datbase contain product price #1#
                                    <td> @modelBillItem[i].TypeProduct?.Product?.ProductName</td>

                                    <td > @modelBillItem[i].TypeProduct?.TypeName</td>


                                    <td> @modelBillItem[i].SizeName</td>

                                    <td>@($"{modelBillItem[i].TypeProduct!.Product!.Price:#,###}")</td>
                                    <td> @modelBillItem[i].Quantity</td>

                                    <td >
                                        <div id="sotientra">@($"{modelBillItem[i].Total:#,###}")</div>
                                    </td>

                                </tr>
                            }

                        </div>
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-end p-3 fw-bold">
                        Tổng Tiền: @($"{Model.Total:#,###}")đ
                    </div>
                </div>
            </div>*@
            <div class="card">
                <div class="card-body">
                    <div class="container mb-5 mt-3">
                        <div class="row d-flex align-items-baseline">
                            <div class="col-xl-9">
                                <p style="color: #7e8d9f;font-size: 20px;">Hóa Đơn > <strong>ID: #@Model.Id[..8]</strong></p>
                            </div>
                            <hr>
                        </div>

                        <div class="container">
                            <div class="col-md-12">


                            </div>


                            <div class="row">
                                <div class="col-xl-8">
                                    <ul class="list-unstyled">
                                        <li class="text-muted">Gửi đến: <span style="color:#5d9fc5 ;">@(user!.LastName + user.FirstName)</span></li>
                                        <li class="text-muted">Đường:</li>
                                        <li class="text-muted">
                                            <i class="fas fa-phone"></i>@user.PhoneNumber
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xl-4">
                                    <p class="text-muted">Hóa đơn</p>
                                    <ul class="list-unstyled">
                                        <li class="text-muted">
                                            <i class="fas fa-circle" style="color:#D84852 ;"></i>
                                            <span
                                                class="fw-bold">
                                                ID:
                                            </span>#@Model.Id[..8]
                                        </li>
                                        <li class="text-muted">
                                            <i class="fas fa-circle" style="color:#D84852 ;"></i>
                                            <span
                                                class="fw-bold">
                                                Tạo vào:
                                            </span>@Model.Date!.Value.ToShortDateString()
                                        </li>
                                        <li class="text-muted">
                                            <i class="fas fa-circle" style="color:#D84852 ;"></i>
                                            <span
                                                class="me-1 fw-bold">
                                                Trạng thái:
                                            </span>
                                            <span class="badge bg-success text-white fw-bold">
                                                Đã thanh toán
                                            </span>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            <div class="row my-2 mx-1 justify-content-center">
                                <table class="table table-striped table-borderless">
                                    <thead style="background-color:#D84852 ;" class="text-white">
                                    <tr>
                                        <th scope="col">STT</th>
                                        <th scope="col">Tên sản phẩm</th>
                                        <th scope="col">Số lượng</th>
                                        <th scope="col">Giá</th>
                                        <th scope="col">Tổng giá</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @{
                                        var billList = Model.BillItems.ToList();
                                    }
                                    @for (var i = 0; i < billList.Count; i++)
                                    {
                                        <tr>
                                            <th scope="row">@(i + 1)</th>
                                            <td>@billList[i].TypeProduct!.Product!.ProductName</td>
                                            <td>@billList[i].Quantity</td>
                                            <td>@($"{billList[i].TypeProduct.Product.Price:#,###}")đ</td>
                                            <td>@($"{billList[i].Total:#,###}")đ</td>
                                        </tr>
                                    }
                                    </tbody>

                                </table>
                            </div>
                            <div class="row">
                                <div class="col-xl-8">

                                </div>
                                <div class="col-xl-3">
                                    <ul class="list-unstyled">
                                        <!--                            <li class="text-muted ms-3"><span class="text-black me-4">SubTotal</span>$1110</li>-->
                                    </ul>
                                    <p class="text-black float-start">
                                        <span class="text-black me-3">Tổng Giá:</span>
                                        <span
                                            style="font-size: 25px;">
                                            @($"{Model.Total:#,###}")đ
                                        </span>
                                    </p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-xl-10">
                                </div>
                                <div class="col-xl-2">
                                    <a asp-controller="Home" asp-action="Index" class="btn btn-primary text-capitalize"
                                            style="background-color:#60bdf3 ;">
                                        Quay về trang chủ
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>